---
spring:
  cloud:
    gateway:
      routes:
      - id: add_request_header_route
        uri: http://localhost:8888/endpoint/endpointA
        filters:
        - AddRequestHeader=md5, 213
        - RequestTime=true
        predicates:
        - After=2019-01-20T17:42:47.789-07:00[America/Denver]
  profiles: add_request_header_route

---
spring:
  cloud:
    gateway:
      routes:
      - id: add_response_header_route
        uri: http://httpbin.org:80/get
        filters:
        - AddResponseHeader=X-Response-Foo, Bar
        predicates:
        - After=2017-01-20T17:42:47.789-07:00[America/Denver]
      - id: ingredients-fallback
          uri: lb://service-hi
          predicates:
          - Path=/fallback
          filters:
          - StripPrefix=1
  profiles: add_response_header_route


---
spring:
  cloud:
    gateway:
      routes:
      - id: rewritepath_route
        uri: https://blog.csdn.net
        predicates:
        - Path=/foo/**
        filters:
        - RewritePath=/foo/(?<segment>.*), /$\{segment}
  profiles: rewritepath_route

---
spring:
  cloud:
    gateway:
      routes:
      - id: request_time_route
        uri: http://httpbin.org:80/get
        filters:
        - RequestTime=false
        predicates:
        - After=2017-01-20T17:42:47.789-07:00[America/Denver]
  profiles: request_time_route
---
spring:
  cloud:
    gateway:
      routes:
      - id: path_route_hys
        uri: http://www.baidu.com/endpoint/endpointB
        predicates:
        - Path=/getmessage
        filters:
        - name: Hystrix
          args:
            name: test_hystrix
            fallbackUri: forward:/fallback
      - id: path_route_pre
        uri: http://www.baidu.com
        predicates:
        - Path=/endpointA
        filters:
        - PrefixPath=/endpoint
      - id: query_route
        uri: http://www.baidu.com/endpoint/endpointB
        predicates:
        - Query=name, shen
        filters:
        - AddRequestHeader=username, test

